### ISSUE TITLE
[DE8] novnc proxy not working with HA deployment

### ISSUE THREAD

**Issue by jcannava** [rcbops/opencenter#443]
nova-novncproxy --config-file=/etc/nova/nova.conf nova
WebSocket server settings:
- Listen on xx:6080
- Flash security policy server
- Web server. Web root: /usr/share/novnc
- No SSL/TLS support (no cert file)
- proxying from xx:6080 to ignore:ignore
  
  1: xx: new handler Process
  1: xx: "OPTIONS / HTTP/1.0" 501 -
  2: xx: new handler Process
  2: handler exception: [Errno 32] Broken pipe
  2: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 774, in top_new_client
    self.client = self.do_handshake(startsock, address)
  File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 705, in do_handshake
    wsh = WSRequestHandler(retsock, address, not self.web)
  File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 937, in **init**
    SimpleHTTPRequestHandler.**init**(self, req, addr, object())
  File "/usr/lib/python2.7/SocketServer.py", line 640, in **init**
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 693, in finish
    self.wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  error: [Errno 32] Broken pipe
  
  3: xx: new handler Process
  3: xx: "OPTIONS / HTTP/1.0" 501 -
  4: xx: new handler Process
  4: handler exception: [Errno 32] Broken pipe
  4: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 774, in top_new_client
    self.client = self.do_handshake(startsock, address)
  File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 705, in do_handshake
    wsh = WSRequestHandler(retsock, address, not self.web)
  File "/usr/lib/python2.7/dist-packages/websockify/websocket.py", line 937, in **init**
    SimpleHTTPRequestHandler.**init**(self, req, addr, object())
  File "/usr/lib/python2.7/SocketServer.py", line 640, in **init**
    self.finish()
  File "/usr/lib/python2.7/SocketServer.py", line 693, in finish
    self.wfile.flush()
  File "/usr/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
  error: [Errno 32] Broken pipe
  
  5: xx: new handler Process
  5: xx: "OPTIONS / HTTP/1.0" 501 -
  6: xx1: new handler Process
  6: handler exception: [Errno 32] Broken pipe

**Comment by mancdaz** [comment]
possibly fixed by https://github.com/rcbops-cookbooks/openstack-ha/pull/24

**Comment by jairaj** [comment]
Negative. 

After updating haproxy & openstack-ha to v1.0.5, I still see:
nova      1440  0.0  0.0      0     0 ?        Z    16:07   0:00 [nova-novncproxy] <defunct>

Haproxy check is one of the two issues. The second issue is causing vnc to not work in HA is due to the value set on compute nodes by chef.  
Current value: vncserver_proxyclient_address=[haproxy ip]
Correct : vncserver_proxyclient_address=[compute node's local IP]

Disabling checks in haproxy configs & updating  vncserver_proxyclient_address in nova.conf on client nodes fixes the issue.
